# Generated by Django 3.2.9 on 2021-11-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20211126_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='scheduled_slots',
            field=models.ManyToManyField(blank=True, to='task.Slot'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='scheduled_slots',
            field=models.ManyToManyField(blank=True, to='task.Slot'),
        ),
    ]
