# Generated by Django 3.2.9 on 2021-11-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20211126_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='interviewer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
