# Generated by Django 3.2.9 on 2021-11-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20211126_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='interview',
            name='title',
            field=models.CharField(default='Technical Round', max_length=100),
        ),
    ]
